package(default_visibility = ["//visibility:public"])

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    deps = [],
)

py_test(
    name = "test_helpers",
    srcs = ["test_helpers.py"],
    size = "small",
    deps = ["//pazel:helpers"],
)
